"""
Configuration module for AI Control Mapping Agent.
Loads environment variables and provides application configuration.
"""

from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import field_validator
from functools import lru_cache
from typing import Optional, Union


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""

    # Application
    app_name: str = "AI Control Mapping Agent"
    app_version: str = "1.0.0"
    debug: bool = False

    # API Settings
    backend_host: str = "localhost"
    backend_port: int = 8000
    api_v1_prefix: str = "/api/v1"

    # Azure Open AI Settings
    azure_openai_endpoint: str
    azure_openai_deployment_name: str = "gpt-5.6-sol"
    azure_openai_fallback_model: str = "gpt-4.1-fallback"
    # Embedding deployment backing semantic policy retrieval. Must match the
    # model the shipped catalog embeddings were generated with; a mismatch
    # disables semantic retrieval rather than comparing incompatible vectors.
    azure_openai_embedding_deployment: str = "text-embedding-3-large"
    azure_openai_api_version: str = "2024-12-01-preview"
    azure_openai_api_key: Optional[str] = None  # If set, uses API key; else DefaultAzureCredential
    azure_openai_request_timeout_seconds: float = 120.0

    # Optional: For user-assigned managed identity
    azure_client_id: Optional[str] = None
    azure_tenant_id: Optional[str] = None

    # Microsoft Graph API Settings (for M365 and Purview)
    graph_api_base_url: str = "https://graph.microsoft.com/v1.0"
    graph_api_beta_url: str = "https://graph.microsoft.com/beta"
    graph_client_id: Optional[str] = None  # App registration for Graph API access
    graph_client_secret: Optional[str] = None  # Client secret (use managed identity in production)

    # Cosmos DB Settings
    cosmos_db_endpoint: Optional[str] = None
    cosmos_db_database_name: str = "compliance-iq-db"

    # Application Insights
    applicationinsights_connection_string: Optional[str] = None

    # Authentication
    enable_auth: bool = False  # Enable Azure AD authentication
    azure_ad_tenant_id: Optional[str] = None
    azure_ad_client_id: Optional[str] = None
    azure_ad_audience: Optional[str] = None  # Defaults to client_id if not set

    # Environment
    environment: str = "development"  # development, staging, production
    log_level: str = "INFO"

    # CORS Settings (can be comma-separated string or list)
    cors_origins: Union[list[str], str] = "http://localhost:8501,http://localhost:3000"
    
    @field_validator('cors_origins', mode='before')
    @classmethod
    def parse_cors_origins(cls, v):
        """Parse CORS origins from comma-separated string or list."""
        if isinstance(v, str):
            return [origin.strip() for origin in v.split(',') if origin.strip()]
        return v

    # Data paths
    mcsb_data_path: str = "data/mcsb/mcsb_v1_controls.json"
    policy_mappings_path: str = "data/mcsb/azure_policy_mappings.json"
    # Bundled external-framework catalogues (CSV). Relative paths are resolved
    # against the backend ``app/`` package dir; absolute paths are used as-is.
    catalogues_dir: str = "data/catalogues"

    # Azure Policy catalog (retrieval corpus for control -> policy mapping).
    # Relative paths are resolved against the backend ``app/`` package dir.
    policy_catalog_path: str = "data/policy_catalog/azure_policy_catalog.json"
    # Precomputed sentence embeddings for the catalog, generated by
    # scripts/generate_policy_catalog_embeddings.py. Absent -> lexical-only.
    policy_catalog_embeddings_path: str = (
        "data/policy_catalog/azure_policy_catalog_embeddings.npz"
    )
    # Fuse dense (embedding) retrieval with TF-IDF. Measured on the NCSP gold
    # mapping, this lifts micro-recall@500 from 86.7% to 95.6% on an expanded
    # query, because regulatory prose and Azure Policy display names share
    # almost no vocabulary. Automatically inert if no embedding artifact loads.
    policy_catalog_semantic_search: bool = True
    # Candidate policy definitions retrieved per control and offered to the LLM
    # for final selection. This is the *post-rerank* window: retrieval itself
    # runs at ``policy_catalog_retrieval_depth``.
    policy_catalog_candidate_count: int = 40
    # Depth of the first-stage retrieval sweep feeding the reranker. Measured
    # against the NCSP gold mapping, micro-recall of the expert's policies rises
    # from 15.6% @15 to 46.7% @200 on the raw control text, so a wide sweep plus
    # a rerank strictly dominates a narrow sweep. See app/tests/test_mapping_recall.py.
    policy_catalog_retrieval_depth: int = 200
    # Restate each control in Azure vocabulary before retrieval. This is the
    # single largest recall lever (the vocabulary of regulatory prose and of
    # Azure Policy display names barely overlap); disable to fall back to
    # querying with the raw control text.
    policy_catalog_query_expansion: bool = True
    # Token ceiling for the (small, structured) control-intent expansion call.
    policy_catalog_expansion_max_tokens: int = 1200
    # Narrow the wide retrieval sweep to the candidate window with an LLM pass
    # before the selection call. Disable to pass retrieval order straight through.
    policy_catalog_rerank: bool = True
    policy_catalog_rerank_max_tokens: int = 2000
    # Score multiplier applied to definitions whose category was predicted by
    # the control-intent expansion. A soft boost, not a filter, so a wrong
    # category prediction degrades ranking instead of removing the right answer.
    policy_catalog_category_boost: float = 1.25
    # Ranking multiplier applied to non-enforceable "Regulatory Compliance"
    # (Microsoft Managed Control / CMA_*) policies during candidate retrieval.
    # These are manual attestation controls with no enforcement logic, so they
    # are demoted (not excluded) below real Audit/Deny policies. 1.0 disables
    # the demotion; lower values push them further down.
    policy_catalog_regulatory_penalty: float = 0.35
    # Best-effort runtime refresh of the catalog from ARM using the backend's
    # managed identity. Off by default; the on-demand refresh endpoint works
    # regardless. Requires the identity to have Reader on a subscription.
    policy_catalog_runtime_refresh: bool = False
    # Subscription used for runtime/on-demand ARM catalog refresh (optional;
    # falls back to the first subscription visible to the identity).
    policy_catalog_refresh_subscription: Optional[str] = None

    # Classify each control's coverage category (A/B/C/D) with a dedicated call
    # that is shown no policy candidates, before retrieval runs. In the NCSP gold
    # mapping only 24/137 controls are Azure-Policy enforceable and 71 are purely
    # organisational, so deciding the control's nature blind is what stops the
    # engine attaching a plausible policy to a governance control.
    coverage_classification: bool = True
    coverage_classification_max_tokens: int = 1500

    # AI Mapping Settings
    ai_temperature: float = 0.3  # Lower for consistency    ai_max_tokens: int = 16000
    ai_batch_size: int = 5  # Process controls in batches
    ai_mapping_max_concurrency: int = 10

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )


@lru_cache
def get_settings() -> Settings:
    """Get cached settings instance."""
    return Settings()
