"""Azure Policy catalog retrieval service.

Loads a snapshot of Azure **built-in** policy definitions (generated by
``scripts/generate_policy_catalog.py``) and provides lightweight TF-IDF search
over it. This is the retrieval corpus that lets the AI mapping engine ground
external framework controls in *real* Azure Policy definition GUIDs, rather than
being limited to the small MCSB control set.

Design notes:
* Dependency-free TF-IDF (no scikit-learn) with an inverted index, so search
  over ~2.5k definitions is fast and the container image stays lean.
* The path is resolved against the backend package dir (mirrors the catalogues
  loader) so it works regardless of the process working directory.
* Missing/empty snapshot degrades gracefully: ``search`` returns ``[]`` and the
  caller falls back to its prior behaviour.
"""
from __future__ import annotations

import asyncio
import json
import logging
import math
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

_TOKEN_RE = re.compile(r"[a-z0-9]+")

# Small English + domain stopword list. Kept short on purpose: aggressive
# stopword removal hurts recall for short control descriptions.
_STOPWORDS = frozenset(
    """
    a an the of to and or for in on at by with from is are be as that this it its
    which must should shall may can will not no ensure enable enabled using use used
    audit require required control policy azure resource resources configure configured
    """.split()
)


@dataclass(frozen=True)
class PolicyCandidate:
    """A retrieved built-in policy definition with its relevance score."""

    name: str  # policy definition GUID
    display_name: str
    description: str
    category: str
    score: float


def _tokenize(text: str) -> List[str]:
    return [
        t for t in _TOKEN_RE.findall((text or "").lower())
        if len(t) > 1 and t not in _STOPWORDS
    ]


# Azure groups Microsoft "Managed Control" (CMA_*) manual-attestation policies
# under this category. They carry no enforcement logic (no audit/deny effect),
# so they are demoted below real enforceable policies during retrieval.
_NON_ENFORCEABLE_CATEGORY = "regulatory compliance"

# Enforcement effects that do nothing on their own. ``Manual`` is the attestation
# placeholder (CMA_* controls); ``Disabled`` is a no-op. A built-in whose
# resolved effect is one of these enforces nothing, so it must not count as
# Azure-Policy coverage regardless of its category. Compared case-folded.
_NON_ENFORCEABLE_EFFECTS = frozenset({"manual", "disabled"})

# Built-in policies in these categories are internal/reserved and CANNOT be added
# to a custom policy set definition — ARM rejects the initiative with
# "can not be part of a custom policy set". Recommending them would produce an
# initiative whose generated PowerShell/CLI fails at deploy time, so they are
# excluded from retrieval and stripped at generation. Compared case-folded.
NON_INCLUDABLE_CATEGORIES = frozenset({"system policy"})


def _is_non_includable_category(category: str) -> bool:
    """True if a built-in in this category cannot be part of a custom policy set."""
    return (category or "").strip().casefold() in NON_INCLUDABLE_CATEGORIES


def _enforcement_weight(category: str, penalty: float) -> float:
    """Ranking multiplier: ``penalty`` for manual-attestation policies, else 1.0."""
    if (category or "").strip().casefold() == _NON_ENFORCEABLE_CATEGORY:
        return penalty
    return 1.0


class PolicyCatalogService:
    """TF-IDF retrieval over the Azure built-in policy definition catalog."""

    def __init__(self, data_path: Optional[str] = None) -> None:
        raw_path = Path(data_path or settings.policy_catalog_path)
        if not raw_path.is_absolute():
            raw_path = Path(__file__).resolve().parent.parent / raw_path
        self.data_path = str(raw_path)

        self._definitions: List[Dict[str, str]] = []
        self._by_name: Dict[str, Dict[str, str]] = {}
        self._doc_terms: List[Dict[str, float]] = []   # per-doc term -> tf weight
        self._doc_norms: List[float] = []
        self._idf: Dict[str, float] = {}
        self._inverted: Dict[str, List[int]] = {}       # term -> doc indices
        self._loaded = False
        self._source = "unloaded"

    # ------------------------------------------------------------------
    # Loading / indexing
    # ------------------------------------------------------------------
    def load(self) -> None:
        if self._loaded:
            return
        path = Path(self.data_path)
        if not path.exists():
            logger.warning(
                "Policy catalog snapshot not found at %s; retrieval disabled "
                "(falling back to empty catalog).", self.data_path,
            )
            self._loaded = True
            self._source = "missing"
            return
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            definitions = data.get("definitions") if isinstance(data, dict) else data
            self._ingest(definitions or [])
            self._source = (
                f"snapshot({data.get('count', len(self._definitions))})"
                if isinstance(data, dict) else "snapshot"
            )
            logger.info(
                "Loaded %d Azure built-in policy definitions for retrieval from %s",
                len(self._definitions), self.data_path,
            )
        except Exception as exc:  # pragma: no cover - defensive
            logger.error("Failed to load policy catalog from %s: %s", self.data_path, exc)
            self._source = "error"
        finally:
            self._loaded = True

    def _ingest(self, definitions: List[Dict[str, str]]) -> None:
        """(Re)build the in-memory index from a list of definition dicts."""
        self._definitions = [
            {
                "name": (d.get("name") or "").strip(),
                "display_name": (d.get("display_name") or "").strip(),
                "description": (d.get("description") or "").strip(),
                "category": (d.get("category") or "Uncategorized").strip(),
                "effect": (d.get("effect") or "").strip(),
                "requires_parameters": bool(d.get("requires_parameters", False)),
                "required_parameters": d.get("required_parameters") or {},
            }
            for d in definitions
            if (d.get("name") or "").strip() and (d.get("display_name") or "").strip()
        ]
        self._by_name = {d["name"]: d for d in self._definitions}
        self._build_index()

    def _build_index(self) -> None:
        n_docs = len(self._definitions)
        doc_freq: Dict[str, int] = {}
        doc_tf: List[Dict[str, int]] = []

        for d in self._definitions:
            # Weight the display name more than the description; include category.
            tokens = (
                _tokenize(d["display_name"]) * 2
                + _tokenize(d["description"])
                + _tokenize(d["category"])
            )
            tf: Dict[str, int] = {}
            for tok in tokens:
                tf[tok] = tf.get(tok, 0) + 1
            doc_tf.append(tf)
            for term in tf:
                doc_freq[term] = doc_freq.get(term, 0) + 1

        self._idf = {
            term: math.log((1 + n_docs) / (1 + df)) + 1.0
            for term, df in doc_freq.items()
        }

        self._doc_terms = []
        self._doc_norms = []
        self._inverted = {}
        for idx, tf in enumerate(doc_tf):
            weights: Dict[str, float] = {}
            for term, count in tf.items():
                w = (1.0 + math.log(count)) * self._idf.get(term, 0.0)
                if w:
                    weights[term] = w
                    self._inverted.setdefault(term, []).append(idx)
            self._doc_terms.append(weights)
            self._doc_norms.append(math.sqrt(sum(w * w for w in weights.values())) or 1.0)

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------
    def search(self, text: str, top_n: Optional[int] = None) -> List[PolicyCandidate]:
        """Return the ``top_n`` most relevant built-in policy definitions."""
        if not self._loaded:
            self.load()
        if not self._definitions:
            return []
        top_n = top_n or settings.policy_catalog_candidate_count

        q_tokens = _tokenize(text)
        if not q_tokens:
            return []
        q_tf: Dict[str, int] = {}
        for tok in q_tokens:
            q_tf[tok] = q_tf.get(tok, 0) + 1
        q_weights = {
            term: (1.0 + math.log(count)) * self._idf.get(term, 0.0)
            for term, count in q_tf.items()
            if self._idf.get(term)
        }
        if not q_weights:
            return []
        q_norm = math.sqrt(sum(w * w for w in q_weights.values())) or 1.0

        scores: Dict[int, float] = {}
        for term, qw in q_weights.items():
            for doc_idx in self._inverted.get(term, ()):  # postings list
                scores[doc_idx] = scores.get(doc_idx, 0.0) + qw * self._doc_terms[doc_idx][term]

        penalty = settings.policy_catalog_regulatory_penalty
        ranked = sorted(
            (
                (
                    idx,
                    (dot / (q_norm * self._doc_norms[idx]))
                    * _enforcement_weight(self._definitions[idx]["category"], penalty),
                )
                for idx, dot in scores.items()
                # Never surface built-ins that cannot be part of a custom policy
                # set (e.g. "System Policy") — recommending them would break the
                # generated deployment scripts.
                if not _is_non_includable_category(self._definitions[idx]["category"])
            ),
            key=lambda t: t[1],
            reverse=True,
        )[:top_n]

        return [
            PolicyCandidate(
                name=self._definitions[idx]["name"],
                display_name=self._definitions[idx]["display_name"],
                description=self._definitions[idx]["description"],
                category=self._definitions[idx]["category"],
                score=round(score, 4),
            )
            for idx, score in ranked
        ]

    def get(self, name: str) -> Optional[Dict[str, str]]:
        if not self._loaded:
            self.load()
        return self._by_name.get(name)

    def is_non_includable(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) is known to be non-includable.

        Returns ``True`` only when the catalog positively identifies the policy
        as belonging to a non-includable category (e.g. "System Policy"). Unknown
        GUIDs return ``False`` — the catalog is a snapshot and may not be
        exhaustive, so we never strip a policy we cannot positively classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        return _is_non_includable_category(entry.get("category", ""))

    def is_non_enforceable(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) is a non-enforceable placeholder.

        Two independent signals classify a built-in as non-enforceable:

        * **Category** — Azure files Microsoft "Managed Control" (CMA_*)
          manual-attestation policies under "Regulatory Compliance".
        * **Effect** — a resolved enforcement effect of ``Manual`` (attestation
          placeholder) or ``Disabled`` (no-op). This catches placeholders that
          are *not* filed under Regulatory Compliance, which the category signal
          alone misses.

        Either way the policy carries no enforcement logic, so mapping a control
        to one produces an initiative that *looks* covered but enforces nothing.

        Returns ``True`` only when the catalog positively classifies the entry.
        Unknown GUIDs return ``False`` — the snapshot may not be exhaustive, so
        we never strip a policy we cannot classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        if (entry.get("category", "") or "").strip().casefold() == _NON_ENFORCEABLE_CATEGORY:
            return True
        return (entry.get("effect", "") or "").strip().casefold() in _NON_ENFORCEABLE_EFFECTS

    def requires_parameters(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) has a required (no-default) parameter.

        Such a built-in cannot be referenced in a custom policy set without
        supplying a value: ARM rejects the set definition with
        ``MissingPolicyParameter``. The generator has no way to invent
        resource-specific values (vault names, regions, workspace IDs), so these
        are excluded at generation to keep the emitted initiative deployable.

        Returns ``True`` only when the catalog positively flags the entry.
        Unknown GUIDs return ``False`` — the snapshot may not be exhaustive, so we
        never strip a policy we cannot positively classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        return bool(entry.get("requires_parameters", False))

    def get_required_parameters(self, name: str) -> Dict[str, Any]:
        """Schema for the parameters a caller must supply for built-in ``name``.

        Returns ``{paramName: {"type": ..., "description": ..., "allowed_values":
        [...]}}`` for every parameter that has no ``defaultValue`` — i.e. the
        values the UI must collect so the built-in can be included with concrete,
        user-supplied literals instead of being excluded. Unknown GUIDs return an
        empty dict.
        """
        entry = self.get(name)
        if not entry:
            return {}
        schema = entry.get("required_parameters") or {}
        return dict(schema) if isinstance(schema, dict) else {}

    def exists(self, name: str) -> bool:
        """Return True if *name* is a real Azure built-in policy definition GUID.

        Accepts a bare GUID or a full
        ``/providers/Microsoft.Authorization/policyDefinitions/<guid>`` id and
        checks only the trailing definition segment.
        """
        if not name:
            return False
        segment = name.strip().rstrip("/").rsplit("/", 1)[-1]
        return self.get(segment) is not None

    @property
    def available(self) -> bool:
        """True when a non-empty built-in catalog is loaded.

        Existence checks (``exists``) are only meaningful when the catalog
        actually loaded; if the snapshot is missing/empty this is ``False`` so
        callers can fall back to format-only validation rather than dropping
        every policy reference.
        """
        if not self._loaded:
            self.load()
        return len(self._definitions) > 0

    @property
    def count(self) -> int:
        if not self._loaded:
            self.load()
        return len(self._definitions)

    @property
    def source(self) -> str:
        return self._source

    # ------------------------------------------------------------------
    # Refresh
    # ------------------------------------------------------------------
    def refresh_from_definitions(self, definitions: List[Dict[str, str]], source: str = "refresh") -> int:
        """Replace the corpus with a freshly fetched set of definitions."""
        self._ingest(definitions)
        self._loaded = True
        self._source = source
        logger.info("Refreshed policy catalog: %d definitions (source=%s)", len(self._definitions), source)
        return len(self._definitions)

    async def refresh_from_arm(self, subscription: Optional[str] = None) -> int:
        """Best-effort live refresh of the catalog from ARM.

        Uses the backend's managed identity (``DefaultAzureCredential``) to list
        built-in policy definitions and rebuild the retrieval index without a
        redeploy. Requires the identity to have Reader on a subscription. Raises
        on failure so callers can report it; the in-memory corpus is only
        replaced on success.
        """
        import httpx
        from ..auth.azure_auth import get_azure_credential

        api_version = "2023-04-01"
        cred = get_azure_credential()
        token = (await asyncio.to_thread(
            cred.get_token, "https://management.azure.com/.default"
        )).token
        headers = {"Authorization": f"Bearer {token}"}
        sub = subscription or settings.policy_catalog_refresh_subscription

        async with httpx.AsyncClient(timeout=60.0) as client:
            if not sub:
                resp = await client.get(
                    "https://management.azure.com/subscriptions?api-version=2022-12-01",
                    headers=headers,
                )
                resp.raise_for_status()
                subs = resp.json().get("value", [])
                if not subs:
                    raise RuntimeError("No subscription visible to the identity for catalog refresh")
                sub = subs[0]["subscriptionId"]

            url = (
                f"https://management.azure.com/subscriptions/{sub}"
                f"/providers/Microsoft.Authorization/policyDefinitions?api-version={api_version}"
            )
            definitions: List[Dict[str, str]] = []
            while url:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                body = resp.json()
                for item in body.get("value", []):
                    props = item.get("properties", {}) or {}
                    if props.get("policyType") != "BuiltIn":
                        continue
                    display = (props.get("displayName") or "").strip()
                    meta = props.get("metadata") or {}
                    version = str(meta.get("version") or "")
                    if display.startswith("[Deprecated]") or "deprecated" in version.lower():
                        continue
                    definitions.append(
                        {
                            "name": (item.get("name") or "").strip(),
                            "display_name": display,
                            "description": (props.get("description") or "").strip(),
                            "category": (meta.get("category") or "Uncategorized").strip(),
                            "mode": (props.get("mode") or "All").strip(),
                        }
                    )
                url = body.get("nextLink")

        if not definitions:
            raise RuntimeError("ARM returned no built-in policy definitions")
        return self.refresh_from_definitions(definitions, source=f"arm({len(definitions)})")


@lru_cache
def get_policy_catalog_service() -> PolicyCatalogService:
    """Get cached policy catalog service instance."""
    service = PolicyCatalogService()
    service.load()
    return service
