"""Azure Policy catalog retrieval service.

Loads a snapshot of Azure **built-in** policy definitions (generated by
``scripts/generate_policy_catalog.py``) and provides hybrid search over it. This
is the retrieval corpus that lets the AI mapping engine ground external framework
controls in *real* Azure Policy definition GUIDs, rather than being limited to the
small MCSB control set.

Retrieval runs two rankers over the **whole** catalog and fuses them:

* **Lexical** — dependency-free TF-IDF with an inverted index. Precise when the
  control and the policy happen to share vocabulary.
* **Semantic** — cosine similarity over precomputed sentence embeddings
  (``scripts/generate_policy_catalog_embeddings.py``). Bridges the vocabulary gap
  between regulatory prose and Azure Policy display names, which lexical search
  structurally cannot.

The two are combined with Reciprocal Rank Fusion, which needs no score
calibration between rankers and degrades to plain lexical search when the
embedding artifact or the embedding deployment is unavailable.

Measured on the NCSP v2.0 gold mapping (``app/tests/test_mapping_recall.py``),
micro-recall of the expert's policies at depth 500:

===================================  ==========
retrieval                            recall@500
===================================  ==========
lexical, raw control text (shipped)      60.0%
lexical, expanded query                  86.7%
hybrid, expanded query                   95.6%
===================================  ==========

Design notes:
* The path is resolved against the backend package dir (mirrors the catalogues
  loader) so it works regardless of the process working directory.
* Missing/empty snapshot degrades gracefully: ``search`` returns ``[]`` and the
  caller falls back to its prior behaviour. A missing *embedding* artifact
  degrades to lexical-only rather than failing.
"""
from __future__ import annotations

import asyncio
import json
import logging
import math
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from ..config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

_TOKEN_RE = re.compile(r"[a-z0-9]+")

# Small English + domain stopword list. Kept short on purpose: aggressive
# stopword removal hurts recall for short control descriptions.
_STOPWORDS = frozenset(
    """
    a an the of to and or for in on at by with from is are be as that this it its
    which must should shall may can will not no ensure enable enabled using use used
    audit require required control policy azure resource resources configure configured
    """.split()
)


@dataclass(frozen=True)
class PolicyCandidate:
    """A retrieved built-in policy definition with its relevance score."""

    name: str  # policy definition GUID
    display_name: str
    description: str
    category: str
    score: float


def _tokenize(text: str) -> List[str]:
    return [
        t for t in _TOKEN_RE.findall((text or "").lower())
        if len(t) > 1 and t not in _STOPWORDS
    ]


# Azure groups Microsoft "Managed Control" (CMA_*) manual-attestation policies
# under this category. They carry no enforcement logic (no audit/deny effect),
# so they are demoted below real enforceable policies during retrieval.
_NON_ENFORCEABLE_CATEGORY = "regulatory compliance"

# Enforcement effects that do nothing on their own. ``Manual`` is the attestation
# placeholder (CMA_* controls); ``Disabled`` is a no-op. A built-in whose
# resolved effect is one of these enforces nothing, so it must not count as
# Azure-Policy coverage regardless of its category. Compared case-folded.
_NON_ENFORCEABLE_EFFECTS = frozenset({"manual", "disabled"})

# Built-in policies in these categories are internal/reserved and CANNOT be added
# to a custom policy set definition — ARM rejects the initiative with
# "can not be part of a custom policy set". Recommending them would produce an
# initiative whose generated PowerShell/CLI fails at deploy time, so they are
# excluded from retrieval and stripped at generation. Compared case-folded.
NON_INCLUDABLE_CATEGORIES = frozenset({"system policy"})


def _is_non_includable_category(category: str) -> bool:
    """True if a built-in in this category cannot be part of a custom policy set."""
    return (category or "").strip().casefold() in NON_INCLUDABLE_CATEGORIES


def _enforcement_weight(category: str, penalty: float) -> float:
    """Ranking multiplier: ``penalty`` for manual-attestation policies, else 1.0."""
    if (category or "").strip().casefold() == _NON_ENFORCEABLE_CATEGORY:
        return penalty
    return 1.0


# Reciprocal Rank Fusion smoothing constant. 60 is the value from the original
# Cormack et al. paper and the de-facto default; it damps the top ranks enough
# that one ranker's confident-but-wrong first hit cannot dominate the fusion.
_RRF_K = 60


def _reciprocal_rank_fusion(
    rankings: Iterable[List[int]], k: int = _RRF_K
) -> List[tuple]:
    """Fuse several ranked index lists into one, best first.

    RRF scores each item by ``sum(1 / (k + rank))`` across the rankings it
    appears in. It uses only *ranks*, never scores, so a TF-IDF cosine and a
    dense cosine can be combined without calibrating one against the other.
    """
    scores: Dict[int, float] = {}
    for ranking in rankings:
        for rank, idx in enumerate(ranking):
            scores[idx] = scores.get(idx, 0.0) + 1.0 / (k + rank + 1)
    return sorted(scores.items(), key=lambda item: item[1], reverse=True)


class PolicyCatalogService:
    """Hybrid (TF-IDF + embedding) retrieval over the Azure built-in policy catalog."""

    def __init__(
        self,
        data_path: Optional[str] = None,
        embeddings_path: Optional[str] = None,
    ) -> None:
        raw_path = Path(data_path or settings.policy_catalog_path)
        if not raw_path.is_absolute():
            raw_path = Path(__file__).resolve().parent.parent / raw_path
        self.data_path = str(raw_path)

        emb_path = Path(embeddings_path or settings.policy_catalog_embeddings_path)
        if not emb_path.is_absolute():
            emb_path = Path(__file__).resolve().parent.parent / emb_path
        self.embeddings_path = str(emb_path)

        self._definitions: List[Dict[str, str]] = []
        self._by_name: Dict[str, Dict[str, str]] = {}
        self._doc_terms: List[Dict[str, float]] = []   # per-doc term -> tf weight
        self._doc_norms: List[float] = []
        self._idf: Dict[str, float] = {}
        self._inverted: Dict[str, List[int]] = {}       # term -> doc indices
        self._embeddings = None                         # np.ndarray | None
        self._embedding_model = ""
        self._embedding_client = None
        self._loaded = False
        self._source = "unloaded"
        self._snapshot_date = ""
        self._initiatives: List[Dict[str, Any]] = []
        self._initiatives_by_name: Dict[str, Dict[str, Any]] = {}
        # definition GUID -> initiative GUIDs that contain it. Built once so
        # "is this already covered by an initiative you have?" is a lookup
        # rather than a scan of 15,000 membership references.
        self._definition_to_initiatives: Dict[str, List[str]] = {}

    # ------------------------------------------------------------------
    # Loading / indexing
    # ------------------------------------------------------------------
    def load(self) -> None:
        if self._loaded:
            return
        path = Path(self.data_path)
        if not path.exists():
            logger.warning(
                "Policy catalog snapshot not found at %s; retrieval disabled "
                "(falling back to empty catalog).", self.data_path,
            )
            self._loaded = True
            self._source = "missing"
            return
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            definitions = data.get("definitions") if isinstance(data, dict) else data
            self._ingest(definitions or [])
            if isinstance(data, dict):
                self._source = f"snapshot({data.get('count', len(self._definitions))})"
                # The date the catalog was captured. Every mapping is only as
                # current as the snapshot it was resolved against, and the
                # analyst workbook's Legend is explicit that region and service
                # availability "changes without customer notice" and must be
                # re-verified per release. A mapping that cannot say when its
                # catalog was taken cannot be defended.
                self._snapshot_date = str(data.get("generated_at") or "")
                self._ingest_initiatives(data.get("initiatives") or [])
            else:
                self._source = "snapshot"
            logger.info(
                "Loaded %d Azure built-in policy definitions for retrieval from %s",
                len(self._definitions), self.data_path,
            )
        except Exception as exc:  # pragma: no cover - defensive
            logger.error("Failed to load policy catalog from %s: %s", self.data_path, exc)
            self._source = "error"
        finally:
            self._loaded = True

    def _ingest(self, definitions: List[Dict[str, str]]) -> None:
        """(Re)build the in-memory index from a list of definition dicts."""
        self._definitions = [
            {
                "name": (d.get("name") or "").strip(),
                "display_name": (d.get("display_name") or "").strip(),
                "description": (d.get("description") or "").strip(),
                "category": (d.get("category") or "Uncategorized").strip(),
                "effect": (d.get("effect") or "").strip(),
                # The effects the definition *allows*, not just its resolved
                # default. 484 built-ins default to Audit but permit Deny;
                # dropping this here silently emptied ``available_effects`` on
                # every mapping, hiding that a control can be blocked rather
                # than merely observed.
                "allowed_effects": [
                    str(effect).strip()
                    for effect in (d.get("allowed_effects") or [])
                    if str(effect).strip()
                ],
                "policy_type": (d.get("policy_type") or "").strip(),
                "requires_parameters": bool(d.get("requires_parameters", False)),
                "required_parameters": d.get("required_parameters") or {},
            }
            for d in definitions
            if (d.get("name") or "").strip() and (d.get("display_name") or "").strip()
        ]
        self._by_name = {d["name"]: d for d in self._definitions}
        self._build_index()
        self._load_embeddings()

    def _build_index(self) -> None:
        n_docs = len(self._definitions)
        doc_freq: Dict[str, int] = {}
        doc_tf: List[Dict[str, int]] = []

        for d in self._definitions:
            # Weight the display name more than the description; include category.
            tokens = (
                _tokenize(d["display_name"]) * 2
                + _tokenize(d["description"])
                + _tokenize(d["category"])
            )
            tf: Dict[str, int] = {}
            for tok in tokens:
                tf[tok] = tf.get(tok, 0) + 1
            doc_tf.append(tf)
            for term in tf:
                doc_freq[term] = doc_freq.get(term, 0) + 1

        self._idf = {
            term: math.log((1 + n_docs) / (1 + df)) + 1.0
            for term, df in doc_freq.items()
        }

        self._doc_terms = []
        self._doc_norms = []
        self._inverted = {}
        for idx, tf in enumerate(doc_tf):
            weights: Dict[str, float] = {}
            for term, count in tf.items():
                w = (1.0 + math.log(count)) * self._idf.get(term, 0.0)
                if w:
                    weights[term] = w
                    self._inverted.setdefault(term, []).append(idx)
            self._doc_terms.append(weights)
            self._doc_norms.append(math.sqrt(sum(w * w for w in weights.values())) or 1.0)

    # ------------------------------------------------------------------
    # Semantic index
    # ------------------------------------------------------------------
    def _load_embeddings(self) -> None:
        """Load the precomputed embedding matrix, if one was shipped.

        Absence is normal and non-fatal: retrieval falls back to lexical-only.
        The artifact records the model and dimension it was generated with; a
        mismatch against the configured deployment disables semantic retrieval
        rather than silently comparing vectors from two different models, which
        would produce confident nonsense.
        """
        self._embeddings = None
        path = Path(self.embeddings_path)
        if not path.exists():
            logger.info(
                "No policy catalog embeddings at %s; retrieval is lexical-only. "
                "Run scripts/generate_policy_catalog_embeddings.py to enable "
                "semantic retrieval.", self.embeddings_path,
            )
            return
        try:
            import numpy as np

            with np.load(path, allow_pickle=False) as bundle:
                vectors = bundle["vectors"]
                names = [str(n) for n in bundle["names"]]
                model = str(bundle["model"]) if "model" in bundle else ""
        except Exception as exc:  # pragma: no cover - defensive
            logger.error("Failed to load policy catalog embeddings from %s: %s", path, exc)
            return

        if len(names) != len(self._definitions):
            logger.warning(
                "Policy catalog embeddings are stale (%d vectors for %d definitions); "
                "semantic retrieval disabled. Regenerate them.",
                len(names), len(self._definitions),
            )
            return

        index_of = {d["name"]: i for i, d in enumerate(self._definitions)}
        if any(n not in index_of for n in names):
            logger.warning(
                "Policy catalog embeddings do not match the loaded definitions; "
                "semantic retrieval disabled. Regenerate them."
            )
            return

        import numpy as np

        # Reorder the shipped vectors onto the definition ordering so row i of the
        # matrix always corresponds to self._definitions[i].
        ordered = np.empty_like(vectors)
        for row, name in enumerate(names):
            ordered[index_of[name]] = vectors[row]
        self._embeddings = ordered.astype(np.float32)
        self._embedding_model = model
        logger.info(
            "Loaded %d policy catalog embeddings (%d dims, model %s) for semantic retrieval",
            ordered.shape[0], ordered.shape[1], model or "unknown",
        )

    @property
    def has_semantic_index(self) -> bool:
        """True when semantic retrieval is available."""
        if not self._loaded:
            self.load()
        return self._embeddings is not None

    @property
    def embedding_matrix(self):
        """The L2-normalised catalog embedding matrix, row-aligned to definitions.

        Exposed for offline evaluation (``app/tests/mapping_recall.py``), which
        reproduces hybrid ranking without a live embedding deployment.
        """
        if not self._loaded:
            self.load()
        return self._embeddings

    def definition_name_at(self, index: int) -> str:
        """The policy GUID at a definition index, matching ``embedding_matrix`` rows."""
        if not self._loaded:
            self.load()
        return self._definitions[index]["name"]

    def _embed_query(self, text: str):
        """Embed a query, or return ``None`` if embeddings are unavailable.

        Never raises: an embedding outage must degrade retrieval to lexical-only,
        not fail the mapping run.
        """
        if self._embeddings is None:
            return None
        try:
            import numpy as np

            from ..auth import get_azure_openai_client

            if self._embedding_client is None:
                self._embedding_client = get_azure_openai_client()
            response = self._embedding_client.embeddings.create(
                model=settings.azure_openai_embedding_deployment,
                input=text[:8000],
                dimensions=self._embeddings.shape[1],
            )
            vector = np.asarray(response.data[0].embedding, dtype=np.float32)
            norm = float(np.linalg.norm(vector))
            return vector / norm if norm else None
        except Exception as exc:  # noqa: BLE001 - semantic search is best-effort
            logger.warning(
                "Query embedding failed (%s); falling back to lexical retrieval "
                "for this query.", exc,
            )
            return None

    def _semantic_ranking(self, text: str, limit: int) -> List[int]:
        """Definition indices ordered by cosine similarity to ``text``."""
        query = self._embed_query(text)
        if query is None:
            return []
        import numpy as np

        sims = self._embeddings @ query
        limit = min(limit, sims.shape[0])
        # argpartition then sort only the head: O(n) instead of sorting all 2465.
        head = np.argpartition(-sims, limit - 1)[:limit]
        return [int(i) for i in head[np.argsort(-sims[head])]]

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------
    def _lexical_ranking(
        self,
        text: str,
        boost_categories: Optional[Iterable[str]] = None,
    ) -> List[int]:
        """Definition indices ordered by boosted TF-IDF cosine score."""
        q_tokens = _tokenize(text)
        if not q_tokens:
            return []
        q_tf: Dict[str, int] = {}
        for tok in q_tokens:
            q_tf[tok] = q_tf.get(tok, 0) + 1
        q_weights = {
            term: (1.0 + math.log(count)) * self._idf.get(term, 0.0)
            for term, count in q_tf.items()
            if self._idf.get(term)
        }
        if not q_weights:
            return []
        q_norm = math.sqrt(sum(w * w for w in q_weights.values())) or 1.0

        scores: Dict[int, float] = {}
        for term, qw in q_weights.items():
            for doc_idx in self._inverted.get(term, ()):  # postings list
                scores[doc_idx] = scores.get(doc_idx, 0.0) + qw * self._doc_terms[doc_idx][term]

        penalty = settings.policy_catalog_regulatory_penalty
        boost_set = {(c or "").strip().casefold() for c in (boost_categories or ()) if c}
        boost = settings.policy_catalog_category_boost if boost_set else 1.0
        ranked = sorted(
            (
                (
                    idx,
                    (dot / (q_norm * self._doc_norms[idx]))
                    * _enforcement_weight(self._definitions[idx]["category"], penalty)
                    * (
                        boost
                        if self._definitions[idx]["category"].strip().casefold() in boost_set
                        else 1.0
                    ),
                )
                for idx, dot in scores.items()
            ),
            key=lambda t: t[1],
            reverse=True,
        )
        return [idx for idx, _ in ranked]

    def search(
        self,
        text: str,
        top_n: Optional[int] = None,
        boost_categories: Optional[Iterable[str]] = None,
        semantic: Optional[bool] = None,
    ) -> List[PolicyCandidate]:
        """Return the ``top_n`` most relevant built-in policy definitions.

        Args:
            text: Query text. Recall is dominated by how closely this matches
                Azure's own vocabulary rather than by ``top_n``, so callers
                should pass an expanded query — see
                ``services/control_intent_service.py``.
            top_n: Result count. Defaults to the configured candidate window.
            boost_categories: Optional catalog categories (e.g. ``{"Key Vault"}``)
                predicted for this control. Definitions in those categories get a
                multiplicative boost in the lexical ranking. Deliberately a boost
                and not a filter: a wrong prediction then degrades ranking rather
                than discarding the correct definition outright.
            semantic: Force semantic fusion on/off. Defaults to the configured
                setting, and is ignored when no embedding artifact is loaded.

        Returns:
            Scored candidates, best first. ``score`` is the fused rank score when
            semantic retrieval contributed, and the TF-IDF cosine otherwise, so
            it is comparable within a result set but not across calls.
        """
        if not self._loaded:
            self.load()
        if not self._definitions:
            return []
        top_n = top_n or settings.policy_catalog_candidate_count

        use_semantic = (
            settings.policy_catalog_semantic_search if semantic is None else semantic
        ) and self._embeddings is not None

        lexical = self._lexical_ranking(text, boost_categories)
        # Fuse over a window wider than the requested one: a definition ranked
        # 300th lexically and 5th semantically should still surface.
        fusion_depth = max(top_n * 3, settings.policy_catalog_retrieval_depth)
        dense = self._semantic_ranking(text, fusion_depth) if use_semantic else []

        if dense:
            scored = _reciprocal_rank_fusion(
                (lexical[:fusion_depth], dense), k=_RRF_K
            )
        else:
            scored = [(idx, 1.0 / (rank + 1)) for rank, idx in enumerate(lexical)]

        results: List[PolicyCandidate] = []
        for idx, score in scored:
            definition = self._definitions[idx]
            # Never surface built-ins that cannot be part of a custom policy set
            # (e.g. "System Policy") — recommending them would break the
            # generated deployment scripts.
            if _is_non_includable_category(definition["category"]):
                continue
            results.append(
                PolicyCandidate(
                    name=definition["name"],
                    display_name=definition["display_name"],
                    description=definition["description"],
                    category=definition["category"],
                    score=round(score, 6),
                )
            )
            if len(results) >= top_n:
                break
        return results

    def get(self, name: str) -> Optional[Dict[str, str]]:
        if not self._loaded:
            self.load()
        return self._by_name.get(name)

    def is_non_includable(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) is known to be non-includable.

        Returns ``True`` only when the catalog positively identifies the policy
        as belonging to a non-includable category (e.g. "System Policy"). Unknown
        GUIDs return ``False`` — the catalog is a snapshot and may not be
        exhaustive, so we never strip a policy we cannot positively classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        return _is_non_includable_category(entry.get("category", ""))

    def is_non_enforceable(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) is a non-enforceable placeholder.

        Two independent signals classify a built-in as non-enforceable:

        * **Category** — Azure files Microsoft "Managed Control" (CMA_*)
          manual-attestation policies under "Regulatory Compliance".
        * **Effect** — a resolved enforcement effect of ``Manual`` (attestation
          placeholder) or ``Disabled`` (no-op). This catches placeholders that
          are *not* filed under Regulatory Compliance, which the category signal
          alone misses.

        Either way the policy carries no enforcement logic, so mapping a control
        to one produces an initiative that *looks* covered but enforces nothing.

        Returns ``True`` only when the catalog positively classifies the entry.
        Unknown GUIDs return ``False`` — the snapshot may not be exhaustive, so
        we never strip a policy we cannot classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        if (entry.get("category", "") or "").strip().casefold() == _NON_ENFORCEABLE_CATEGORY:
            return True
        return (entry.get("effect", "") or "").strip().casefold() in _NON_ENFORCEABLE_EFFECTS

    def requires_parameters(self, name: str) -> bool:
        """True if the built-in ``name`` (GUID) has a required (no-default) parameter.

        Such a built-in cannot be referenced in a custom policy set without
        supplying a value: ARM rejects the set definition with
        ``MissingPolicyParameter``. The generator has no way to invent
        resource-specific values (vault names, regions, workspace IDs), so these
        are excluded at generation to keep the emitted initiative deployable.

        Returns ``True`` only when the catalog positively flags the entry.
        Unknown GUIDs return ``False`` — the snapshot may not be exhaustive, so we
        never strip a policy we cannot positively classify.
        """
        entry = self.get(name)
        if not entry:
            return False
        return bool(entry.get("requires_parameters", False))

    def get_required_parameters(self, name: str) -> Dict[str, Any]:
        """Schema for the parameters a caller must supply for built-in ``name``.

        Returns ``{paramName: {"type": ..., "description": ..., "allowed_values":
        [...]}}`` for every parameter that has no ``defaultValue`` — i.e. the
        values the UI must collect so the built-in can be included with concrete,
        user-supplied literals instead of being excluded. Unknown GUIDs return an
        empty dict.
        """
        entry = self.get(name)
        if not entry:
            return {}
        schema = entry.get("required_parameters") or {}
        return dict(schema) if isinstance(schema, dict) else {}

    def exists(self, name: str) -> bool:
        """Return True if *name* is a real Azure built-in policy definition GUID.

        Accepts a bare GUID or a full
        ``/providers/Microsoft.Authorization/policyDefinitions/<guid>`` id and
        checks only the trailing definition segment.
        """
        if not name:
            return False
        segment = name.strip().rstrip("/").rsplit("/", 1)[-1]
        return self.get(segment) is not None

    @property
    def available(self) -> bool:
        """True when a non-empty built-in catalog is loaded.

        Existence checks (``exists``) are only meaningful when the catalog
        actually loaded; if the snapshot is missing/empty this is ``False`` so
        callers can fall back to format-only validation rather than dropping
        every policy reference.
        """
        if not self._loaded:
            self.load()
        return len(self._definitions) > 0

    @property
    def count(self) -> int:
        if not self._loaded:
            self.load()
        return len(self._definitions)

    # ── Initiatives ──────────────────────────────────────────────────
    #
    # Azure ships compliance coverage as initiatives, not loose definitions:
    # Microsoft cloud security benchmark, NIST SP 800-53 Rev. 5, ISO 27001 and
    # CIS Foundations are all policy *set* definitions. A catalog of
    # definitions alone could never answer "this is already covered by an
    # initiative you have assigned", and would report a perfectly real
    # initiative GUID as an unresolvable identifier - the silent-drop failure
    # mode, wearing a different hat.

    def _ingest_initiatives(self, initiatives: List[Dict[str, Any]]) -> None:
        self._initiatives = [i for i in initiatives if i.get("name")]
        self._initiatives_by_name = {i["name"]: i for i in self._initiatives}
        index: Dict[str, List[str]] = {}
        for init in self._initiatives:
            for guid in init.get("policy_definition_names") or []:
                index.setdefault(guid, []).append(init["name"])
        self._definition_to_initiatives = index

    def get_initiative(self, name: str) -> Optional[Dict[str, Any]]:
        """Look up a built-in initiative by GUID, accepting a full ARM id."""
        if not self._loaded:
            self.load()
        if not name:
            return None
        segment = name.strip().rstrip("/").rsplit("/", 1)[-1]
        return self._initiatives_by_name.get(segment)

    def initiative_exists(self, name: str) -> bool:
        return self.get_initiative(name) is not None

    def identifier_exists(self, name: str) -> bool:
        """True if *name* is a real built-in definition **or** initiative.

        Validation that only knows definitions calls a real initiative GUID
        invalid, which is how a correct answer gets discarded as a typo.
        """
        return self.exists(name) or self.initiative_exists(name)

    def initiatives_containing(self, name: str) -> List[Dict[str, Any]]:
        """Built-in initiatives that already include definition *name*.

        This is what lets the product say "you do not need to assign this
        policy separately - it ships inside MCSB, which you already run."
        """
        if not self._loaded:
            self.load()
        if not name:
            return []
        segment = name.strip().rstrip("/").rsplit("/", 1)[-1]
        return [
            self._initiatives_by_name[i]
            for i in self._definition_to_initiatives.get(segment, [])
            if i in self._initiatives_by_name
        ]

    @property
    def initiative_count(self) -> int:
        if not self._loaded:
            self.load()
        return len(self._initiatives)

    @property
    def initiatives_available(self) -> bool:
        """Whether initiative coverage can be asserted at all.

        False means "not loaded", never "not covered" - reporting an absent
        index as an absence of coverage would be the same lie as a silent drop.
        """
        return self.initiative_count > 0

    @property
    def source(self) -> str:
        return self._source

    @property
    def snapshot_date(self) -> str:
        """When the catalog this mapping resolved against was captured.

        Empty when unknown, which is itself worth reporting: an undated
        catalog cannot support a claim about what Azure offers today.
        """
        if not self._loaded:
            self.load()
        return self._snapshot_date

    # ------------------------------------------------------------------
    # Refresh
    # ------------------------------------------------------------------
    def refresh_from_definitions(self, definitions: List[Dict[str, str]], source: str = "refresh") -> int:
        """Replace the corpus with a freshly fetched set of definitions."""
        self._ingest(definitions)
        self._loaded = True
        self._source = source
        # A refresh makes the snapshot date *now*, and leaving the old one in
        # place would attribute fresh definitions to a stale capture.
        self._snapshot_date = datetime.now(timezone.utc).isoformat()
        logger.info("Refreshed policy catalog: %d definitions (source=%s)", len(self._definitions), source)
        return len(self._definitions)

    async def refresh_from_arm(self, subscription: Optional[str] = None) -> int:
        """Best-effort live refresh of the catalog from ARM.

        Uses the backend's managed identity (``DefaultAzureCredential``) to list
        built-in policy definitions and rebuild the retrieval index without a
        redeploy. Requires the identity to have Reader on a subscription. Raises
        on failure so callers can report it; the in-memory corpus is only
        replaced on success.
        """
        import httpx
        from ..auth.azure_auth import get_azure_credential

        api_version = "2023-04-01"
        cred = get_azure_credential()
        token = (await asyncio.to_thread(
            cred.get_token, "https://management.azure.com/.default"
        )).token
        headers = {"Authorization": f"Bearer {token}"}
        sub = subscription or settings.policy_catalog_refresh_subscription

        async with httpx.AsyncClient(timeout=60.0) as client:
            if not sub:
                resp = await client.get(
                    "https://management.azure.com/subscriptions?api-version=2022-12-01",
                    headers=headers,
                )
                resp.raise_for_status()
                subs = resp.json().get("value", [])
                if not subs:
                    raise RuntimeError("No subscription visible to the identity for catalog refresh")
                sub = subs[0]["subscriptionId"]

            url = (
                f"https://management.azure.com/subscriptions/{sub}"
                f"/providers/Microsoft.Authorization/policyDefinitions?api-version={api_version}"
            )
            definitions: List[Dict[str, str]] = []
            while url:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                body = resp.json()
                for item in body.get("value", []):
                    props = item.get("properties", {}) or {}
                    if props.get("policyType") != "BuiltIn":
                        continue
                    display = (props.get("displayName") or "").strip()
                    meta = props.get("metadata") or {}
                    version = str(meta.get("version") or "")
                    if display.startswith("[Deprecated]") or "deprecated" in version.lower():
                        continue
                    definitions.append(
                        {
                            "name": (item.get("name") or "").strip(),
                            "display_name": display,
                            "description": (props.get("description") or "").strip(),
                            "category": (meta.get("category") or "Uncategorized").strip(),
                            "mode": (props.get("mode") or "All").strip(),
                        }
                    )
                url = body.get("nextLink")

        if not definitions:
            raise RuntimeError("ARM returned no built-in policy definitions")
        return self.refresh_from_definitions(definitions, source=f"arm({len(definitions)})")


@lru_cache
def get_policy_catalog_service() -> PolicyCatalogService:
    """Get cached policy catalog service instance."""
    service = PolicyCatalogService()
    service.load()
    return service
